### ISSUE TITLE
锐捷虚拟网卡，捕捉数据包失败

### ISSUE THREAD

**Issue by deku772** [tkkcc/mentohust#2]
!! 在网卡macvlan1上获取IP失败!
!! 在网卡macvlan1上获取子网掩码失败!
** 本机MAC:	e6:74:55:71:0c:ae
** 使用IP:	0.0.0.0
** 子网掩码:	255.255.255.0
>> 寻找服务器...
** 认证MAC:	00:1a:a9:17:ff:ff
>> 发送用户名...
>> 发送密码...
>> 认证成功!
>> 发送心跳包以保持在线...
!! 捕获数据包失败，请检查网络连接！
>> 认证已退出。

**Comment by tagwu0227** [comment]
我也遇到这个问题了，请问解决了吗
